In [7]:
import pandas as pd
import pycountry

In [2]:
# this contains information about the countries of the world
world_data_df = pd.read_csv('world-data-2023.csv') # from kaggle; global country information https://www.kaggle.com/datasets/nelgiriyewithana/countries-of-the-world-2023

# this contains information about the immigration/emigration rates of the countries of the world including demogrphics of the country's emigrants and immigrants and the regional classification of the country
emigration_immigration_rates_df = pd.read_excel('Migration-Rates-2000-2010-2020/emigration-immigration-rates.xlsx') # from https://thedocs.worldbank.org/en/doc/c36d19e775a2b700ae94e879ef83b253-0050062023/original/Migration-Rates-2000-2010-2020.zip

# this contains information on the destination and origin of migrants, categorized by gender and quantified by the number of those migrants sharing the same origin and destination
migration_matrix_df = pd.read_excel('Global-Migration-Matrix-1960-2020/WBMM_1960_2020.xlsx') # from https://thedocs.worldbank.org/en/doc/00700f3fc0f4eb17bdc08a372a4a2a13-0050062023/original/Global-Migration-Matrix-1960-2020.zip

Correcting and supplementing 3 letter codes

In [ ]:
# immigration_df = pd.DataFrame(columns=['Xcountry', 'Xabb', 'Xregion10', 'Xyear', 'Xtotal_pop', 'total_immi', 'Xtotal_immi_male', 'Xtotal_immi_female','Xbirth_rate', 
#                                        'Xinfant_mortality', 'Xnum_physicians', 'Xlife_exp', 'Xoop_healthcare', 'Xgdp', 'Xunemployement',
#                                        'Xminimum_wage', 'Xpschool_enrollment', 'Xtschool_enrollment', 'Xhs_immi_male', 'Xhs_immi_female', 'Xhs_immi_total', 'Xhs_male', 'Xhs_female',
#                                        'Xhs_total', 'Xlabor', 'Xhs_labor', 'Xnhs_labor', 'Xpopm014', 'Xpopf014', 'Ximmi_m014', 'Ximmi_f014'])

immigration_df = pd.DataFrame()

# print(len(world_data_df))
# print(len(emigration_immigration_rates_df[emigration_immigration_rates_df['year'] == 2020]))

country_to_abbr = {country.name: country.alpha_3 for country in pycountry.countries}
manual_corrections = {
    "The Bahamas": "BHS",
    "Bolivia": "BOL",
    "Brunei": "BRN",
    "Ivory Coast": "CIV",
    "Cape Verde": "CPV",
    "Republic of the Congo": "COG",
    "Czech Republic": "CZE",
    "Democratic Republic of the Congo": "COD",
    "The Gambia": "GMB",
    "Vatican City": "VAT",
    "Iran": "IRN",
    "Republic of Ireland": "IRL",
    "Laos": "LAO",
    "Federated States of Micronesia": "FSM",
    "Moldova": "MDA",
    "North Korea": "PRK",
    "South Korea": "KOR",
    "Syria": "SYR",
    "Tanzania": "TZA",
    "East Timor": "TLS",
    "Turkey": "TUR",
    "Venezuela": "VEN",
    "Vietnam": "VNM",
    "Russia": "RUS",
    "Palestine": "PSE"
}

country_to_abbr.update(manual_corrections)
# world_data_df.loc[150, 'Country'] = "Sao Tome and Principe"
# world_data_df.loc[133, 'Country'] = "Palestine"
world_data_df["Abbreviation"] = world_data_df["Country"].map(country_to_abbr)
world_data_df[world_data_df["Abbreviation"].isnull()]["Country"]

Series([], Name: Country, dtype: object)

In [26]:
immigration_df['country'] = world_data_df['Country']
immigration_df['abb'] = world_data_df['Abbreviation']
immigration_df['birth_rate'] = world_data_df['Birth Rate']
immigration_df['fertility_rate'] = world_data_df['Fertility Rate']
immigration_df['gdp'] = world_data_df['GDP']
immigration_df['pschool_enrollment'] = world_data_df['Gross primary education enrollment (%)']
immigration_df['tschool_enrollment'] = world_data_df['Gross tertiary education enrollment (%)']
immigration_df['infant_mortality'] = world_data_df['Infant mortality']
immigration_df['life_expectancy'] = world_data_df['Life expectancy']
immigration_df['maternal_mortality_ratio'] = world_data_df['Maternal mortality ratio']
immigration_df['minimum_wage'] = world_data_df['Minimum wage']
immigration_df['oop_healthcare'] = world_data_df['Out of pocket health expenditure']
immigration_df['physicians_per1000'] = world_data_df['Physicians per thousand']
immigration_df['population'] = world_data_df['Population']
immigration_df['unemployment'] = world_data_df['Unemployment rate']
immigration_df

,country,abb,birth_rate,fertility_rate,gdp,pschool_enrollment,tschool_enrollment,infant_mortality,life_expectancy,maternal_mortality_ratio,minimum_wage,oop_healthcare,physicians_per1000,population,unemployment
0,Afghanistan,AFG,32.49,4.47,"$19,101,353,833",104.00%,9.70%,47.9,64.5,638.0,$0.43,78.40%,0.28,"38,041,754",11.12%
1,Albania,ALB,11.78,1.62,"$15,278,077,447",107.00%,55.00%,7.8,78.5,15.0,$1.12,56.90%,1.20,"2,854,191",12.33%
2,Algeria,DZA,24.28,3.02,"$169,988,236,398",109.90%,51.40%,20.1,76.7,112.0,$0.95,28.10%,1.72,"43,053,054",11.70%
3,Andorra,AND,7.20,1.27,"$3,154,057,987",106.40%,NaN,2.7,NaN,NaN,$6.63,36.40%,3.33,"77,142",NaN
4,Angola,AGO,40.73,5.52,"$94,635,415,870",113.50%,9.30%,51.6,60.8,241.0,$0.71,33.40%,0.21,"31,825,295",6.89%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,VEN,17.88,2.27,"$482,359,318,768",97.20%,79.30%,21.4,72.1,125.0,$0.01,45.80%,1.92,"28,515,829",8.80%
191,Vietnam,VNM,16.75,2.05,"$261,921,244,843",110.60%,28.50%,16.5,75.3,43.0,$0.73,43.50%,0.82,"96,462,106",2.01%
192,Yemen,YEM,30.45,3.79,"$26,914,402,224",93.60%,10.20%,42.9,66.1,164.0,NaN,81.00%,0.31,"29,161,922",12.91%
193,Zambia,ZMB,36.19,4.63,"$23,064,722,446",98.70%,4.10%,40.4,63.5,213.0,$0.24,27.50%,1.19,"17,861,030",11.43%
194,Zimbabwe,ZWE,30.68,3.62,"$21,440,758,800",109.90%,10.00%,33.9,61.2,458.0,NaN,25.80%,0.21,"14,645,468",4.95%

In [41]:
immigration_stats_df = emigration_immigration_rates_df[['country', 'year', 'region10_ori', 'iso3', 'Immigrants_males', 'Immigrants_females',
                                                        'Immigrants_males_HS', 'Immigrants_females_HS', 'Immigrants_HS_total', 'Labor_males_HS', 
                                                        'Labor_females_HS', 'Labor_HS', 'Labor', 'Labor_LS', 'Labor_females_LS', 'Labor_males_LS', 
                                                        'popf014', 'popm014', 'Immigrants_014_female', 'Immigrants_014_male']]
immigration_stats_df_2020 = immigration_stats_df[immigration_stats_df['year'] == 2020]
# merge 2020 immigration stats with world data
immi_try = pd.merge(immigration_df, immigration_stats_df_2020, left_on='abb', right_on='iso3', how='left')
immi_try

,country_x,abb,birth_rate,fertility_rate,gdp,pschool_enrollment,tschool_enrollment,infant_mortality,life_expectancy,maternal_mortality_ratio,...,Labor_females_HS,Labor_HS,Labor,Labor_LS,Labor_females_LS,Labor_males_LS,popf014,popm014,Immigrants_014_female,Immigrants_014_male
0,Afghanistan,AFG,32.49,4.47,"$19,101,353,833",104.00%,9.70%,47.9,64.5,638.0,...,195448.0,1124901.0,22647496.0,21522594.0,10809482.0,10729555.0,7947146.0,8333700.0,11065.0,8352.0
1,Albania,ALB,11.78,1.62,"$15,278,077,447",107.00%,55.00%,7.8,78.5,15.0,...,92899.0,218361.0,2348722.0,2130361.0,1069069.0,1061504.0,231501.0,257626.0,3946.0,4231.0
2,Algeria,DZA,24.28,3.02,"$169,988,236,398",109.90%,51.40%,20.1,76.7,112.0,...,1494801.0,2734122.0,30352152.0,27618030.0,13593534.0,14018136.0,6608900.0,6889992.0,15376.0,16873.0
3,Andorra,AND,7.20,1.27,"$3,154,057,987",106.40%,NaN,2.7,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2256.0,2237.0
4,Angola,AGO,40.73,5.52,"$94,635,415,870",113.50%,9.30%,51.6,60.8,241.0,...,34679.0,82270.0,17617840.0,17535570.0,8980643.0,8554850.0,7590076.0,7658353.0,12009.0,16401.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,VEN,17.88,2.27,"$482,359,318,768",97.20%,79.30%,21.4,72.1,125.0,...,2316526.0,3705871.0,20683548.0,16977676.0,8339556.0,8594542.0,3794930.0,3957465.0,117716.0,110717.0
191,Vietnam,VNM,16.75,2.05,"$261,921,244,843",110.60%,28.50%,16.5,75.3,43.0,...,1351767.0,3059255.0,74761840.0,71702584.0,36715452.0,34992352.0,10673109.0,11903637.0,5793.0,7913.0
192,Yemen,YEM,30.45,3.79,"$26,914,402,224",93.60%,10.20%,42.9,66.1,164.0,...,175297.0,653861.0,18243880.0,17590020.0,8950011.0,8650424.0,5675675.0,5906414.0,29328.0,40759.0
193,Zambia,ZMB,36.19,4.63,"$23,064,722,446",98.70%,4.10%,40.4,63.5,213.0,...,41543.0,115165.0,10291816.0,10176651.0,5230427.0,4946757.0,4008980.0,4083160.0,9809.0,10605.0
194,Zimbabwe,ZWE,30.68,3.62,"$21,440,758,800",109.90%,10.00%,33.9,61.2,458.0,...,90895.0,285258.0,8633707.0,8348450.0,4577572.0,3781451.0,3102450.0,3126770.0,10275.0,11178.0